version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
      - image: circleci/redis:4.0.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i npm@6
      - run: npm -s i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm -s test

